### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by ippocratis** [jackyzy823/chromium-sync-server#1]
Can you please elaborate the required steps to selfhosted the chromium.sync server?
I'm curent'y using Firefox syncserver with Firefox but I'm exited by founding this project.
Thanks

**Comment by jackyzy823** [comment]
Hello, this project is just in experimental status. There're lots of disadvantages like : 1. Currently , account login is not implemented because of lacking oauth provider. 2. This does not work for Chrome in Android , because Chrome use android built-in **Google/GMS** account system , you can't change it  and that's the main reason that i can not continue on this project.

So generally I'd recommend you continue to use firefox's stack.

If you really like Chromium-based browser, you could use brave browser instead. This project code is mostly based on [brave's one](https://github.com/brave/go-sync). and brave's one is able to self host (haven't tested yet).

**Comment by ippocratis** [comment]
Yeah I've seen https://github.com/brave/go-sync#readme
But still not sure if the server endpoint is configurable for android
On the other hand Mozilla have moved to syncstorage-rs and there are.no clear instructions how to self store it
Anyway
Thanks

**Comment by jackyzy823** [comment]
> On the other hand Mozilla have moved to syncstorage-rs and there are.no clear instructions how to self store it

Although syncserver is deprecated , the sync protocol is not. so you can still use it for a long time to wait for them making syncstorage-rs's document clear enough for self hosting and migration.




> But still not sure if the server endpoint is configurable for android

Currently and maybe for a long time, **no**. see https://github.com/brave/brave-browser/issues/12314
